spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # sout
        format_sql: true # sout
        default_batch_fetch_size: 1

logging:
  level:
    org.hibernate.sql: debug # logger
    ## org.hibernate.type: trace # parameter binding check -> p6spy ?? ??